### ISSUE TITLE
doppeltes https://

### ISSUE THREAD

**Issue by tabea42** [je4/revcatfront#1]
Offenbar wird vor die URL im BangBang Formular ein https:// automatisch geschrieben.
Bittte prüfen, ob die eingegebene URL schon http oder https enthält.
Beispiel für Fehler: https://mediathek.hgk.fhnw.ch/performance/detail/bangbang-1694/ 
Formular: https://intern.hgk.fhnw.ch/pma/tbl_select.php?db=application&table=formdata

**Comment by je4** [comment]
die url prüfung beim sync war nicht korrekt. nach nächstem sync sollte das problem gelöst sein

**Comment by je4** [comment]
Geht noch nicht
