### ISSUE TITLE
Linebrealks in Beschreibung

### ISSUE THREAD

**Issue by tabea42** [je4/revcatfront#3]
In Beschreibung werden keine Linebreaks angezeigt sonder alles immer weiter 

https://mediathek.hgk.fhnw.ch/amp/detail/bangbang-0208

**Comment by je4** [comment]
bitte den link prüfen. nicht nachvollziehbar...

**Comment by tabea42** [comment]
https://mediathek.hgk.fhnw.ch/performance/detail/bangbang-0207/de

Eine Frau im Cocktail-Kleid sitzt gelangweilt in einem kleinen Raum. Plötzlich stemmt sie ihren Körper zwischen Decke und Boden und nimmt mit zunehmender Anstrengung immer akrobatischere Stellungen ein, deren Sinn sich nicht unmittelbar erschließt. Langsam geht die Orientierung verloren, es ist nicht mehr ersichtlich, was oben und was unten ist. Der Kasten bietet Raum für erstaunliche Bewegungen, die bis zur Erschöpfung getrieben werden. 

>>> hier steht in der DB ein Linebreak

A woman wearing a cocktail dress is sitting bored in a small room. Suddenly she stems her body between the ceiling and the floor. With increasing effort, her positions, whose meaning is enigmatic, become more and more acrobatically contorted. Gradually, we lose our orientation, can no longer tell what is up and what is down. The box offers room for astonish- ing movements that are pursued to exhaustion.

**Comment by je4** [comment]
falls keine html-elemente im abstract gefunden werden, werden linebtreaks nun mit <br> ergänzt
