### ISSUE TITLE
Bitte prüfen, ob Rechtschreibfehler

### ISSUE THREAD

**Issue by tabea42** [je4/revcatfront#6]
Hier:
https://github.com/je4/revcatfront/blob/main/config/active.de.toml#L30

Zweile 31 steht title statt titel?

titel = "Titel"
title = "Sammlungen Performance Kunst Schweiz"

ist das korrekt?

**Comment by je4** [comment]
etwas unschön.

title == titel der webseite
titel == "Titel" als überschrift in der tabellenansicht der suche
